name: Build

on:
  pull_request:
    branches:
      - main

concurrency:
  # Grouped by ref (branch/tag name) not to cancel other jobs running for other feature branches
  group: build_${{ github.ref }}
  # > cancel any currently running job or workflow in the same concurrency group
  # in case of multiple pushes to the same branch, we just need the latest, so cancel all previous
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      go_version: 1.21

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install go ${{ env.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=60s

      - name: Run tests
        run: |
          make test

      - name: Build binary
        run: |
          CGO_ENABLED=0 make build
